### ISSUE TITLE
losing some code

### ISSUE THREAD

**Issue by ChangShiba** [MicrosoftDocs/bot-docs.zh-tw#7]
some code sections are losing
it shows
"Bots/StateManagementBot.cs [!code-csharpStateManagement]",
"Bots/StateManagementBot.cs [!code-csharpStateAccessors]",
"Bots/StateManagementBot.cs [!code-csharpOnMessageActivityAsync]"
"Bots/StateManagementBot.cs [!code-csharpOnTurnAsync]"
thanks!!

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: e18bc52f-7eaf-a473-1cba-9b7c83bd0025
* Version Independent ID: c1b6cf03-c236-cfbf-aa4b-96961b816bc3
* Content: [儲存使用者和對話資料 - Bot Service](https://docs.microsoft.com/zh-tw/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs.zh-tw/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by srvbpigh** [comment]
Hello, @ChangShiba
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
